[chaos-go]
repo="git@github.com:oneiro-ndev/chaoschain.git"
logical="github.com/oneiro-ndev/chaoschain"
label="master"

[chaostool]
repo="git@github.com:oneiro-ndev/chaostool.git"
logical="github.com/oneiro-ndev/chaostool"
label="master"

[whitelist]
repo="git@github.com:oneiro-ndev/whitelist.git"
logical="github.com/oneiro-ndev/whitelist"
label="master"
